/** Mirrors backend/src/common/enums/permission.enum.ts's PERMISSION_CATALOG keys. */
export const PERMISSIONS = {
  BRANDING_EDIT: "settings.branding.edit",
  ORDER_HOURS_EDIT: "settings.order-hours.edit",
  NOTIFICATIONS_EDIT: "settings.notifications.edit",
  PAYMENT_EDIT: "settings.payment.edit",
  DELIVERY_ZONES_EDIT: "settings.delivery-zones.edit",
  CONTENT_EDIT: "settings.content.edit",
  MENU_MANAGE: "menu.manage",
  ORDERS_MANAGE: "orders.manage",
  ORDERS_CANCEL_REFUND: "orders.cancel-refund",
  ORDERS_MANUAL_CREATE: "orders.manual-create",
  PAYMENTS_MANUAL_RECORD: "payments.manual-record",
  DELIVERY_MANAGE: "delivery.manage",
  SUBSCRIPTIONS_MANAGE: "subscriptions.manage",
  SUBSCRIPTIONS_CANCEL_REFUND: "subscriptions.cancel-refund",
  SUBSCRIPTIONS_MANUAL_CREATE: "subscriptions.manual-create",
  SUBSCRIPTIONS_ACT_ON_BEHALF: "subscriptions.act-on-behalf",
  STAFF_MANAGE: "staff.manage",
  PROMOTIONS_MANAGE: "promotions.manage",
  CUSTOMERS_VIEW: "customers.view",
  NOTIFICATION_TEMPLATES_EMAIL_EDIT: "notification-templates.email.edit",
  NOTIFICATION_TEMPLATES_WHATSAPP_EDIT: "notification-templates.whatsapp.edit",
  DINE_IN_MANAGE: "dine-in.manage",
  DINE_IN_ORDER_CREATE: "dine-in.order-create",
} as const;
